spring:
  application:
    name: store
  jwt:
    secret: ${JWT_SECRET}
    accessTokenValiditySeconds: 900 #15m
    refreshTokenValiditySeconds: 604800 #7d
  profiles:
    active: dev
stripe:
  secretKey: ${STRIPE_SECRET_KEY}
  webhookSecretKey: ${STRIPE_WEBHOOK_SECRET_KEY}
websiteUrl: http://localhost:4242